//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoralesFiFthCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductName { get; set; }
        public string description { get; set; }
        public string CategoryName { get; set; }
        public byte[] ProductImg { get; set; }
        public string BuyerName { get; set; }
        public string SellerName { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual User User { get; set; }
    }
}
