//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoralesFiFthCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserProductDetails
    {
        public string username { get; set; }
        public string password { get; set; }
        public string roleName { get; set; }
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ProductID { get; set; }
        public byte[] ProductImg { get; set; }
    }
}
